include: package:lint/analysis_options.yaml

linter:
  rules:
    use_key_in_widget_constructors: false
    avoid_classes_with_only_static_members: false
    avoid_multiple_declarations_per_line: false
    use_build_context_synchronously: false
    sort_pub_dependencies: false
    avoid_bool_literals_in_conditional_expressions: false
